### ISSUE TITLE
hello?

### ISSUE THREAD

**Issue by sean-madhavan** [adel-tahir14/sayan#1]

**Comment by adel-tahir14** [comment]
can't find the password for codeknight github

**Comment by sean-madhavan** [comment]
account seems to be blocked by several attempt!

**Comment by adel-tahir14** [comment]
plz resume it and send me pwd hint

**Comment by sean-madhavan** [comment]
we might need to wait. anyway the password might be fifa or dual

**Comment by sean-madhavan** [comment]
no slack btw?

**Comment by adel-tahir14** [comment]
no

**Comment by sean-madhavan** [comment]
when will you be able to talk?

**Comment by adel-tahir14** [comment]
confirm the pwd and let me know when i can login

**Comment by adel-tahir14** [comment]
did u got an email from ssh?

**Comment by sean-madhavan** [comment]
he says that person didn't reply. i think i need to withdraw today. its exceeding dangerous limit

**Comment by sean-madhavan** [comment]
what do you think?

**Comment by adel-tahir14** [comment]
gimme few days more

**Comment by sean-madhavan** [comment]
okay. i will pause it until sunday then

**Comment by sean-madhavan** [comment]
did you receive g2k?

**Comment by adel-tahir14** [comment]
no, from whom?

**Comment by sean-madhavan** [comment]
call my home. i wrote that i am sending to brother because it is brought by rj

**Comment by adel-tahir14** [comment]
ok, rj's here?

**Comment by sean-madhavan** [comment]
yes. should be arrived yesterday

**Comment by sean-madhavan** [comment]
thanks for handling ssh 2800

**Comment by sean-madhavan** [comment]
btw please note that 6-6-3-7 will be sent

**Comment by sean-madhavan** [comment]
does that sound okay?

**Comment by adel-tahir14** [comment]
ok
